[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["otf_api*"]

[project]
name = "otf-api"
version = "0.0.1"
description = "Python OrangeTheory Fitness API Client"
readme = "README.md"
requires-python = ">=3.8"


classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: Libraries :: Application Frameworks",
    "Topic :: Software Development :: Libraries",
    "Topic :: Internet :: WWW/HTTP",
    "Operating System :: OS Independent",
]

dependencies = [
    "aiohttp==3.9.5",
    "loguru==0.7.2",
    "pydantic==2.7.3",
    "pycognito==2024.5.1",
]


[project.optional-dependencies]
dev = [
    "pytest==8.2.2",
    "pytest-loguru==0.4.0",
    "pytest-asyncio==0.23.7",
    "aioresponses==0.7.6",
    "tox==4.15.1",
    "pytest-cov==5.0.0",
    "build==1.2.1",
    "ruff==0.4.8",
    "pre-commit==3.7.1",
    "mypy==1.10.0",
    "twine==5.1.0",
]
docs = [
    "mkdocs==1.6.0",
    "mkdocs-autorefs==1.0.1",
    "mkdocs-gen-files==0.5.0",
    "mkdocs-get-deps==0.2.0",
    "mkdocs-include-markdown-plugin==6.2.0",
    "mkdocs-literate-nav==0.6.1",
    "mkdocs-material==9.5.26",
    "mkdocs-material-extensions==1.3.1",
    "mkdocs-section-index==0.3.9",
    "mkdocstrings==0.25.1",
    "mkdocstrings-python==1.10.3",
    "griffe-fieldz==0.1.2",
    "mike==2.1.1",
    "setuptools",
    "pkginfo",
    "virtualenv",

]
[tools.pytest.ini_options]
pythonpath = ["src"]
